id = "teralang"
name = "TeraLang"
version = "0.1.0"
schema_version = 1
authors = ["noClaps <contact@zerolimits.dev>"]
description = "TeraLang extension for Zed"
repository = "https://github.com/noClaps/teralang-zed"

[grammars.teralang]
repository = "https://github.com/noClaps/tree-sitter-teralang"
rev = "49d26ab38cb2fbdb0049f27f130a190f2bb7a301"
